# Generated by Django 5.0.6 on 2025-10-26 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('initial_difficulty', models.CharField(max_length=20)),
                ('current_difficulty', models.FloatField(default=1.0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('questions_count', models.IntegerField(default=10)),
                ('time_per_question', models.IntegerField(default=30)),
                ('use_adaptive_difficulty', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz Session',
                'verbose_name_plural': 'Quiz Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('correct_answer', models.CharField(max_length=500)),
                ('wrong_answer_1', models.CharField(max_length=500)),
                ('wrong_answer_2', models.CharField(max_length=500)),
                ('wrong_answer_3', models.CharField(max_length=500)),
                ('explanation', models.TextField()),
                ('difficulty_level', models.CharField(choices=[('łatwy', 'Łatwy'), ('średni', 'Średni'), ('trudny', 'Trudny')], default='średni', max_length=20)),
                ('embedding_vector', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz_app.quizsession')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField()),
                ('response_time', models.FloatField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz_app.question')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'ordering': ['-answered_at'],
                'indexes': [models.Index(fields=['question', 'user'], name='quiz_app_an_questio_99a372_idx'), models.Index(fields=['-answered_at'], name='quiz_app_an_answere_1b0db3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['-started_at'], name='quiz_app_qu_started_2be838_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['user', 'is_completed'], name='quiz_app_qu_user_id_67c182_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['session', 'created_at'], name='quiz_app_qu_session_45d5ed_idx'),
        ),
    ]
